"""empty message

Revision ID: 53dd7d5b4ae
Revises: 312ed935da9
Create Date: 2015-03-23 15:59:07.886643

"""

# revision identifiers, used by Alembic.
revision = '53dd7d5b4ae'
down_revision = '312ed935da9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_admin')
    ### end Alembic commands ###
